#!/bin/bash
# imports
. enVar.sh
. utils.sh

# Variables
CHANNEL_NAME="mychannel"
CHAINCODE_NAME="Certificate"
CHAINCODE_VERSION="2.0"
CHAINCODE_PATH="../artifacts/src/github.com/chaincodes/go/Product/"
ORDERER_ADDRESS="orderer.certs.com:7050"
PEER_ADDRESS="peer0.superadmin.certs.com:7051"
CORE_PEER_LOCALMSPID="SuperadminMSP"
CORE_PEER_TLS_ROOTCERT_FILE=$PEER0_SUPERADMIN_CA
CORE_PEER_MSPCONFIGPATH=${PWD}/../artifacts/channel/crypto-config/peerOrganizations/superadmin.certs.com/users/Admin@superadmin.certs.com/msp

# Install new chaincode version on peer
docker exec -e "CORE_PEER_LOCALMSPID=$CORE_PEER_LOCALMSPID" \
            -e "CORE_PEER_TLS_ROOTCERT_FILE=$CORE_PEER_TLS_ROOTCERT_FILE" \
            -e "CORE_PEER_MSPCONFIGPATH=$CORE_PEER_MSPCONFIGPATH" \
            -e "CORE_PEER_ADDRESS=$PEER_ADDRESS" \
            cli peer chaincode install -n $CHAINCODE_NAME -v $CHAINCODE_VERSION -p $CHAINCODE_PATH
            
# Upgrade chaincode on channel
docker exec -e "CORE_PEER_LOCALMSPID=$CORE_PEER_LOCALMSPID" \
            -e "CORE_PEER_TLS_ROOTCERT_FILE=$CORE_PEER_TLS_ROOTCERT_FILE" \
            -e "CORE_PEER_MSPCONFIGPATH=$CORE_PEER_MSPCONFIGPATH" \
            -e "CORE_PEER_ADDRESS=$PEER_ADDRESS" \
            cli peer chaincode upgrade -o $ORDERER_ADDRESS --tls --cafile $ORDERER_CA \
            -C $CHANNEL_NAME -n $CHAINCODE_NAME -v $CHAINCODE_VERSION \
            -P "OR ('SuperadminMSP.peer','CompanyMSP.peer')"
            
echo "Chaincode upgraded successfully"